services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    depends_on:
      - postgres
      - qdrant
      # - memory-service
      # - ollama

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=llm_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qwen-embedder:
    build:
      context: ../qwen_embedding
      dockerfile: Dockerfile
    container_name: qwen-embedder
    ports:
      - "8050:8050"
    restart: unless-stopped

  
  mcp:
    build:
      context: .
      dockerfile: docker/mcp.Dockerfile
    container_name: mcp-jira-outlook
    command: python -m uvicorn app:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    environment:
      - JIRA_URL=http://host.docker.internal:8080
      - JIRA_USER=admin
      - JIRA_TOKEN=admin
      - OUTLOOK_CLIENT_ID=your_client_id
      - OUTLOOK_CLIENT_SECRET=your_client_secret
      - OUTLOOK_TENANT_ID=your_tenant_id
    volumes:
      - ./MCP:/app
    working_dir: /app

volumes:
  postgres_data:
  qdrant_data:
  ollama_data:
  redis_data:

networks:
  default:
    driver: bridge 