services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env.docker
    environment:
      - ENVIRONMENT=development
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ENABLE_QWEN_RERANKER=false
      - PRELOAD_QWEN_RERANKER=false
    user: root
    depends_on:
      - postgres
      - qdrant
      - redis
      # - memory-service
      # - ollama

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=llm_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qwen-embedder:
    build:
      context: ../qwen_embedding
      dockerfile: Dockerfile
    container_name: qwen-embedder
    ports:
      - "8050:8050"
    restart: unless-stopped


  mcp:
    build:
      context: ../MCP/MCP
      dockerfile: Dockerfile
    container_name: mcp-jira-outlook
    command: python -m uvicorn app:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    env_file:
      - ../MCP/MCP/.env
    volumes:
      - ../MCP/MCP:/app
    working_dir: /app

  mcp-gmail:
    build:
      context: ./simple_gmail_mcp
      dockerfile: Dockerfile
    container_name: mcp-gmail
    stdin_open: true
    tty: false
    restart: unless-stopped


volumes:
  postgres_data:
  qdrant_data:
  ollama_data:
  redis_data:
  mcp-gmail:

networks:
  default:
    driver: bridge 