services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    privileged: true
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ../MCP:/mcp-servers
    env_file:
      - .env.docker
    environment:
      - MCP_SERVERS_PATH=/mcp-servers
      - ENVIRONMENT=development
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ENABLE_QWEN_RERANKER=false
      - PRELOAD_QWEN_RERANKER=false
      - PATH=/usr/local/bin:/opt/homebrew/bin:/usr/local/sbin:/usr/bin:/sbin:/bin
    user: root
    depends_on:
      - postgres
      - qdrant
      - redis
      - clickhouse  # Required for Langfuse analytics
      # - memory-service
      # - ollama

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=llm_platform
      - POSTGRES_MULTIPLE_DATABASES=llm_platform,langfuse,langflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qwen-embedder:
    build:
      context: ../qwen_embedding
      dockerfile: Dockerfile
    container_name: qwen-embedder
    ports:
      - "8050:8050"
    restart: unless-stopped


  mcp-gmail:
    build:
      context: ./simple_gmail_mcp
      dockerfile: Dockerfile
    container_name: mcp-gmail
    stdin_open: true
    tty: false
    restart: unless-stopped

  # ClickHouse for Langfuse analytics (required for v3)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: jarvis-clickhouse
    ports:
      - "8123:8123"    # HTTP interface
      - "9009:9009"    # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=langfuse
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse_password
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # Langfuse Web Application  
  langfuse-web:
    image: langfuse/langfuse:2
    container_name: jarvis-langfuse-web
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      # Database Configuration (separate Langfuse database)
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/langfuse_new
      - DIRECT_URL=postgresql://postgres:postgres@postgres:5432/langfuse_new
      
      # Langfuse Configuration
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=langfuse-secret-key-change-in-production
      - SALT=langfuse-salt-change-in-production
      
      # Optional: Enable debug mode
      - NODE_ENV=development
    restart: unless-stopped

  # Langfuse Worker (not needed for v2 - background processing is handled by web service)
  # langfuse-worker:
  #   image: langfuse/langfuse:2
  #   container_name: jarvis-langfuse-worker
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     # Database Configuration (separate Langfuse database)
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/langfuse
  #     
  #     # Langfuse Configuration  
  #     - NEXTAUTH_SECRET=langfuse-secret-key-change-in-production
  #     - SALT=langfuse-salt-change-in-production
  #   command: ["worker"]
  #   restart: unless-stopped



volumes:
  postgres_data:
  qdrant_data:
  ollama_data:
  redis_data:
  clickhouse_data:
  mcp-gmail:

networks:
  default:
    driver: bridge 