version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    depends_on:
      - postgres
      - qdrant
      # - memory-service
      # - ollama

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=llm_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # memory-service:
  #   image: supermemory/supermemory:latest  # Official Supermemory image
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - MEMORY_SERVICE_CONFIG=development

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   environment:
  #     - OLLAMA_MODELS=qwen3:30b-a3b  # Preload Qwen3-30B-A3B model

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qwen-embedder:
    build:
      context: ../qwen_embedding
      dockerfile: Dockerfile
    container_name: qwen-embedder
    ports:
      - "8050:8050"
    restart: unless-stopped

  web:
    build:
      context: ./llm-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./llm-ui:/app
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
  qdrant_data:
  ollama_data:
  redis_data:

networks:
  default:
    driver: bridge 